/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

 
 // The plan: In the fibonacci sequence you have two numbers, and you add them together.
 // The first number will be 1, and then 2. This leaves you with '3' as the sum.
 // You then take '3' and add it to the number that precedes it - 2. Then 5 with 3, etc.
 // For this program I'll have two variables, and a sum variable. 
 
 
 // PseudoCode for Fibonacci Sequence
 
 // (a) Add var1 and var2 and set sum to the value returned. (1 + 2 = 3; var1 + var2 = sum)
 // (b) Set var1 to var2. (var1 = 2, var2 = 2, sum = 3)
 // (c) Set var2 to sum. (var1 = 2, var2 = 3, sum = 3)
 
 // What's Left?
 // I need to check sum on every iteration - if sum is even valued, we take it and add it to our 'fibsum' variable.
 // Simple if statement

#include<stdio.h>

int main(void){
 
 //These three will be for our Fibonacci sequence.
int var1 = 1;
int var2 = 2;
int sum = 0;

 //fibsum is for storing the sum of all even outputs of the sequence.
int fibsum = 0;
 
 while(sum <= 4000000){
     
     sum = var1 + var2; //(a)
     var1 = var2;       //(b)
     var2 = sum;        //(c)
     
     
     if(sum % 2 == 0){ // Our if statement, which will allow us to collect all of the even 'sum's and add them together.
         
            fibsum += sum;
         
     }

 }
    printf("%d",fibsum);
    return 0;
}
